exports.seed = function (knex) {
  return knex("menu")
    .del()
    .then(function () {
      return knex("menu").insert([
        {
          name: "Spaghetti Carbonara",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Pasta, eggs, pancetta, Pecorino cheese, black pepper",
          description: "A classic Italian pasta dish",
          image: "platePlaceholder.jpg",
          categories: "7",
        },
        {
          name: "Grilled Salmon",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Salmon fillet, lemon, garlic, herbs",
          description: "Freshly grilled salmon with herbs",
          image: "platePlaceholder.jpg",
          categories: "1,8,10",
        },
        {
          name: "Margherita Pizza",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Pizza dough, tomato sauce, mozzarella cheese, basil",
          description: "A simple and delicious pizza",
          image: "platePlaceholder.jpg",
          categories: "2,9",
        },
        {
          name: "Chicken Alfredo",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Fettuccine, chicken, cream sauce, Parmesan cheese",
          description: "Creamy pasta with grilled chicken",
          image: "platePlaceholder.jpg",
          categories: "4,6",
        },
        {
          name: "Caesar Salad",
          price: (Math.random() * 100).toFixed(2),
          ingredients:
            "Romaine lettuce, croutons, Parmesan cheese, Caesar dressing",
          description: "Classic Caesar salad",
          image: "platePlaceholder.jpg",
          categories: "1,2,3",
        },
        {
          name: "Beef Tacos",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Ground beef, tortillas, lettuce, salsa, cheese",
          description: "Delicious beef tacos",
          image: "platePlaceholder.jpg",
          categories: "5,7,9",
        },
        {
          name: "Pasta Primavera",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Pasta, mixed vegetables, garlic, olive oil",
          description: "A fresh and flavorful pasta dish",
          image: "platePlaceholder.jpg",
          categories: "3,5",
        },
        {
          name: "Mushroom Risotto",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Arborio rice, mushrooms, white wine, Parmesan cheese",
          description: "Creamy mushroom risotto",
          image: "platePlaceholder.jpg",
          categories: "6,8",
        },
        {
          name: "BBQ Ribs",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Pork ribs, BBQ sauce, coleslaw, baked beans",
          description: "Finger-licking good BBQ ribs",
          image: "platePlaceholder.jpg",
          categories: "4,10",
        },
        {
          name: "Greek Salad",
          price: (Math.random() * 100).toFixed(2),
          ingredients:
            "Cucumbers, tomatoes, olives, feta cheese, Greek dressing",
          description: "A refreshing Greek salad",
          image: "platePlaceholder.jpg",
          categories: "1,3,5",
        },
        {
          name: "Sushi Platter",
          price: (Math.random() * 100).toFixed(2),
          ingredients:
            "Assorted sushi rolls, soy sauce, wasabi, pickled ginger",
          description: "Fresh and delicious sushi",
          image: "platePlaceholder.jpg",
          categories: "2,4,9",
        },
        {
          name: "Chicken Curry",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Chicken, curry sauce, rice, naan bread",
          description: "A flavorful chicken curry dish",
          image: "platePlaceholder.jpg",
          categories: "1,5,7",
        },
        {
          name: "Shrimp Scampi",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Shrimp, garlic, white wine, butter, parsley",
          description: "Garlicky and buttery shrimp scampi",
          image: "platePlaceholder.jpg",
          categories: "2,6,8",
        },
        {
          name: "Vegetable Stir-Fry",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Assorted vegetables, soy sauce, ginger, rice",
          description: "A healthy and tasty stir-fry",
          image: "platePlaceholder.jpg",
          categories: "3,7,9",
        },
        {
          name: "Cheeseburger",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Beef patty, cheese, lettuce, tomato, ketchup, bun",
          description: "A classic cheeseburger",
          image: "platePlaceholder.jpg",
          categories: "1,2,6",
        },
        {
          name: "Chicken Fajitas",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Chicken, bell peppers, onions, tortillas, sour cream",
          description: "Sizzling chicken fajitas",
          image: "platePlaceholder.jpg",
          categories: "4,7,9",
        },
        {
          name: "Eggplant Parmesan",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Eggplant, marinara sauce, mozzarella cheese, pasta",
          description: "A hearty and cheesy dish",
          image: "platePlaceholder.jpg",
          categories: "3,5,8",
        },
        {
          name: "Seafood Paella",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Rice, shrimp, mussels, squid, saffron, bell peppers",
          description: "A Spanish seafood specialty",
          image: "platePlaceholder.jpg",
          categories: "2,4,6",
        },
        {
          name: "Beef Stroganoff",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Beef, mushrooms, sour cream, onions, egg noodles",
          description: "A creamy and savory beef dish",
          image: "platePlaceholder.jpg",
          categories: "1,5,8",
        },
        {
          name: "Caprese Salad",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Tomatoes, mozzarella cheese, basil, balsamic glaze",
          description: "A simple and delightful Italian salad",
          image: "platePlaceholder.jpg",
          categories: "1,2,10",
        },
        {
          name: "Chicken Quesadilla",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Chicken, cheese, onions, peppers, tortillas",
          description: "A cheesy and savory quesadilla",
          image: "platePlaceholder.jpg",
          categories: "3,5,7",
        },
        {
          name: "Vegetable Curry",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Assorted vegetables, curry sauce, rice",
          description: "A flavorful and spicy vegetable curry",
          image: "platePlaceholder.jpg",
          categories: "1,2,8",
        },
        {
          name: "Tiramisu",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Ladyfingers, coffee, mascarpone cheese, cocoa",
          description: "A classic Italian dessert",
          image: "platePlaceholder.jpg",
          categories: "2,4,10",
        },
        {
          name: "Sushi Platter",
          price: (Math.random() * 100).toFixed(2),
          ingredients:
            "Assorted sushi rolls, soy sauce, wasabi, pickled ginger",
          description: "Fresh and delicious sushi",
          image: "platePlaceholder.jpg",
          categories: "3,6,9",
        },
        {
          name: "Lobster Bisque",
          price: (Math.random() * 100).toFixed(2),
          ingredients: "Lobster, cream, sherry, herbs",
          description: "A rich and creamy lobster soup",
          image: "platePlaceholder.jpg",
          categories: "1,5,7",
        },
        {
          name: "Gyros",
          price: (Math.random() * 100).toFixed(2),
          ingredients:
            "Grilled meat, pita bread, tomatoes, onions, tzatziki sauce",
          description: "A Greek specialty",
          image: "platePlaceholder.jpg",
          categories: "3,6,8",
        },
      ]);
    });
};
