exports.seed = function (knex) {
  return knex("menu_categories")
    .del()
    .then(function () {
      return knex("menu_categories").insert([
        { plate_id: 1, category_id: 7 },
        { plate_id: 2, category_id: 1 },
        { plate_id: 2, category_id: 8 },
        { plate_id: 2, category_id: 10 },
        { plate_id: 3, category_id: 2 },
        { plate_id: 3, category_id: 9 },
        { plate_id: 4, category_id: 4 },
        { plate_id: 4, category_id: 6 },
        { plate_id: 5, category_id: 1 },
        { plate_id: 5, category_id: 2 },
        { plate_id: 5, category_id: 3 },
        { plate_id: 6, category_id: 5 },
        { plate_id: 6, category_id: 7 },
        { plate_id: 6, category_id: 9 },
        { plate_id: 7, category_id: 4 },
        { plate_id: 7, category_id: 8 },
        { plate_id: 8, category_id: 6 },
        { plate_id: 8, category_id: 10 },
        { plate_id: 9, category_id: 1 },
        { plate_id: 9, category_id: 3 },
        { plate_id: 9, category_id: 5 },
        { plate_id: 10, category_id: 2 },
        { plate_id: 10, category_id: 4 },
        { plate_id: 10, category_id: 9 },
        { plate_id: 11, category_id: 6 },
        { plate_id: 11, category_id: 7 },
        { plate_id: 11, category_id: 8 },
        { plate_id: 12, category_id: 3 },
        { plate_id: 12, category_id: 5 },
        { plate_id: 12, category_id: 10 },
        { plate_id: 13, category_id: 1 },
        { plate_id: 13, category_id: 4 },
        { plate_id: 13, category_id: 10 },
        { plate_id: 14, category_id: 3 },
        { plate_id: 14, category_id: 6 },
        { plate_id: 14, category_id: 8 },
        { plate_id: 15, category_id: 1 },
        { plate_id: 15, category_id: 2 },
        { plate_id: 15, category_id: 9 },
        { plate_id: 16, category_id: 4 },
        { plate_id: 16, category_id: 7 },
        { plate_id: 16, category_id: 9 },
        { plate_id: 17, category_id: 1 },
        { plate_id: 17, category_id: 2 },
        { plate_id: 17, category_id: 6 },
        { plate_id: 18, category_id: 5 },
        { plate_id: 18, category_id: 8 },
        { plate_id: 18, category_id: 10 },
        { plate_id: 19, category_id: 3 },
        { plate_id: 19, category_id: 7 },
        { plate_id: 19, category_id: 9 },
        { plate_id: 20, category_id: 5 },
        { plate_id: 20, category_id: 7 },
        { plate_id: 20, category_id: 9 },
        { plate_id: 21, category_id: 1 },
        { plate_id: 21, category_id: 4 },
        { plate_id: 21, category_id: 10 },
        { plate_id: 22, category_id: 3 },
        { plate_id: 22, category_id: 6 },
        { plate_id: 22, category_id: 8 },
      ]);
    });
};
